apiVersion: v1
kind: Namespace
metadata:
  name: autofix-demo
  namespace: default
  labels:
    app: autofix-demo
    owner: platform
    team: platform
    environment: dev
    app.kubernetes.io/name: autofix-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-no-memory-limit
  namespace: autofix-demo
  labels:
    app: test-no-memory-limit
    owner: platform
    team: platform
    environment: dev
    app.kubernetes.io/name: test-no-memory-limit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-no-memory-limit
  template:
    metadata:
      labels:
        app: test-no-memory-limit
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.25
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
            runAsUser: 1000
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
          imagePullPolicy: IfNotPresent
