apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: clue-test
  labels:
    app: hello-world-deployment
    app.kubernetes.io/name: hello-world-deployment
    app.kubernetes.io/instance: hello-world-deployment
    app.kubernetes.io/managed-by: clue
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
        app.kubernetes.io/name: hello-world-deployment
        app.kubernetes.io/instance: hello-world-deployment
        app.kubernetes.io/managed-by: clue
    spec:
      containers:
        - name: hello-world
          image: hashicorp/http-echo
          args:
            - '-text=Hello, World!'
            - '-listen=:5000'
          ports:
            - containerPort: 5000
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: clue-test
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
